name: Upload CSV to Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - 'data/*.csv'   # Only run when CSV files change

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Azure CLI
      uses: azure/setup-azure@v1

    - name: Upload CSV to Blob Storage
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        az storage blob upload \
          --file ./data/sample_data.csv \
          --container-name raw-data \
          --name myfolder/sample_data.csv \
          --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
